### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ServerDeveloper9447** [zaida04/guilded.js#244]
**Describe the bug**
It is just a syntax error in the package.

**To Reproduce**

1. Install guilded.js@0.23.5 using npm
2. Add the necessary code
3. Run it using `node index.js`
**Expected behavior**
The bot should start up.

**Screenshots**
![image](https://github.com/zaida04/guilded.js/assets/86161882/450f3031-f775-440a-af4c-f4301a9031e1)
**Please complete the following information**

-   NodeJS version (`node -v`): 16.7.0
-   NPM version (`npm -v`): 7.20.3
-   Package version (`npm ls guilded.js`): 0.23.5

**Additional context**
Null

**Comment by zaida04** [comment]
Assuming this was solved for you, but for anyone in the future that comes across this issue, it's likely an issue with using an outdated Node.JS version below LTS (18.17.1).

**Comment by ServerDeveloper9447** [comment]
> Assuming this was solved for you, but for anyone in the future that comes across this issue, it's likely an issue with using an outdated Node.JS version below LTS (18.17.1).

The issue is not solved. I just saw that this isn't the repo for the pkg that was throwing the error.
